trigger:
  - master

pool:
  name: 'Default'

variables:
  - group: SqlCreds
  - name: testSqlInstance
    value: 'techpc'
  - name: prodSqlInstance
    value: 'techpc'
  - name: scriptPath
    value: '$(Build.SourcesDirectory)/scripts/releases'
  - name: system.debug
    value: true

stages:
  - stage: Build
    jobs:
      - job: ValidateScripts
        timeoutInMinutes: 10
        steps:
          - powershell: |
              Write-Host "Current working directory: $PWD"
              Write-Host "Listing files in $(Build.SourcesDirectory):"
              Get-ChildItem -Path "$(Build.SourcesDirectory)"
            displayName: 'List Files in Sources Directory'
          - powershell: |
              Write-Host "Listing environment variables:"
              Get-ChildItem env: | Where-Object { $_.Name -like "*SQL*" }
            displayName: 'List Environment Variables'
          - powershell: '.\debug-variables.ps1'
            displayName: 'Debug Variables'
            workingDirectory: '$(Build.SourcesDirectory)'
          - powershell: |
              Write-Host "Updating dbatools to the latest version..."
              Uninstall-Module -Name dbatools -AllVersions -Force -ErrorAction Continue
              # Also manually remove module folders in case Uninstall-Module fails
              Remove-Item -Path "C:\Program Files\WindowsPowerShell\Modules\dbatools" -Recurse -Force -ErrorAction SilentlyContinue
              Remove-Item -Path "C:\Program Files (x86)\WindowsPowerShell\Modules\dbatools" -Recurse -Force -ErrorAction SilentlyContinue
              Remove-Item -Path "$env:USERPROFILE\Documents\WindowsPowerShell\Modules\dbatools" -Recurse -Force -ErrorAction SilentlyContinue
              Install-Module -Name dbatools -Force -Scope CurrentUser -AllowClobber -SkipPublisherCheck -ErrorAction Stop
              Import-Module -Name dbatools -Force -ErrorAction Stop
              $updatedModule = Get-Module -ListAvailable -Name dbatools | Sort-Object Version -Descending | Select-Object -First 1
              Write-Host "Updated dbatools version: $($updatedModule.Version) at $($updatedModule.ModuleBase)"
              $loadedModule = Get-Module -Name dbatools
              Write-Host "Loaded dbatools version: $($loadedModule.Version) at $($loadedModule.ModuleBase)"
            displayName: 'Update dbatools'
          - powershell: |
              Write-Host "Creating validation database..."
              Set-DbatoolsConfig -FullName sql.connection.trustcert -Value $true -Register
              Set-DbatoolsConfig -FullName sql.connection.encrypt -Value $false -Register
              $cred = New-Object System.Management.Automation.PSCredential ("$(SqlUsername)", (ConvertTo-SecureString "$(SqlPassword)" -AsPlainText -Force))
              
              # Drop the database if it exists to ensure a clean state
              Write-Host "Dropping ValidationDB if it exists..."
              $dropQuery = "IF EXISTS (SELECT * FROM sys.databases WHERE name = 'ValidationDB') BEGIN ALTER DATABASE ValidationDB SET SINGLE_USER WITH ROLLBACK IMMEDIATE; DROP DATABASE ValidationDB; END"
              try {
                  Invoke-DbaQuery -SqlInstance "$(testSqlInstance)" -Query $dropQuery -SqlCredential $cred -EnableException
                  Write-Host "ValidationDB dropped successfully."
              }
              catch {
                  Write-Warning "Failed to drop ValidationDB database: $_"
                  throw "Failed to drop ValidationDB: $_"
              }

              # Manually delete the database files if they still exist
              $mdfPath = "D:\SQLData\MSSQL16.MSSQLSERVER\MSSQL\DATA\ValidationDB.mdf"
              $ldfPath = "D:\SQLData\MSSQL16.MSSQLSERVER\MSSQL\DATA\ValidationDB_log.ldf"
              if (Test-Path $mdfPath) {
                  Write-Host "Deleting existing ValidationDB.mdf file..."
                  Remove-Item -Path $mdfPath -Force -ErrorAction Stop
              }
              if (Test-Path $ldfPath) {
                  Write-Host "Deleting existing ValidationDB_log.ldf file..."
                  Remove-Item -Path $ldfPath -Force -ErrorAction Stop
              }

              # Create the database with explicit file locations
              Write-Host "Creating ValidationDB database..."
              $createQuery = "CREATE DATABASE ValidationDB ON (NAME = ValidationDB, FILENAME = 'D:\SQLData