     if exist "D:\actions-runner\_work\Devops_cicd\Devops_cicd" (
            rmdir /s /q "D:\actions-runner\_work\Devops_cicd\Devops_cicd"
          )
      - uses: actions/checkout@v3
        with:
          clean: true
          fetch-depth: 0
      - name: Deploy to Dev
        run: |
          for %%f in (scripts\releases\ddl\*.sql scripts\releases\dml\*.sql scripts\releases\stored_procs\*.sql) do (
            sqlcmd -S prod-sql -d devDb -U ${{ secrets.DB_USER }} -P ${{ secrets.DB_PASSWORD }} -i "%%f"
          )

  DeployToQA:
    needs: DeployToDev
    runs-on: windows-latest
    steps:
      - name: Clear Runner Cache
        run: |
          echo "Clearing runner cache..."
          if exist "D:\actions-runner\_work\Devops_cicd\Devops_cicd" (
            rmdir /s /q "D:\actions-runner\_work\Devops_cicd\Devops_cicd"
          )
      - uses: actions/checkout@v3
        with:
          clean: true
          fetch-depth: 0
      - name: Deploy to QA
        run: |
          for %%f in (scripts\releases\ddl\*.sql scripts\releases\dml\*.sql scripts\releases\stored_procs\*.sql) do (
            sqlcmd -S prod-sql -d qaDb -U ${{ secrets.DB_USER }} -P ${{ secrets.DB_PASSWORD }} -i "%%f"
          )

  DeployToProd:
    needs: DeployToQA
    runs-on: windows-latest
