name: 020-manual-input-workflow


on:
  workflow_dispatch:

     inputs:
        name:

           description: 'person to greet'

           default: 'World'

           required: true

jobs:

  greet:

     runs-on: windows-latest


     steps:

     - name: send greeting
       run: echo "Hello${{ GitHub.event.inputs.name }}"


